/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatIcon: typeof import('./src/components/icons/ChatIcon.vue')['default']
    ContactIcon: typeof import('./src/components/icons/ContactIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    EmojiIcon: typeof import('./src/components/icons/EmojiIcon.vue')['default']
    FileIcon: typeof import('./src/components/icons/FileIcon.vue')['default']
    FileTransfer: typeof import('./src/components/FileTransfer.vue')['default']
    FileTransferProgress: typeof import('./src/components/FileTransferProgress.vue')['default']
    FileUploadDialog: typeof import('./src/components/FileUploadDialog.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    FriendAvatar: typeof import('./src/components/FriendAvatar.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LogoutIcon: typeof import('./src/components/icons/LogoutIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/common/SearchInput.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
